### ISSUE TITLE
IA07

### ISSUE THREAD

**Issue by RavinduSachintha** [codezilla2018/ideapool#6]
Should it be implemented using only WiFi technology?
Can I use something else such as Bluetooth or Mobile Data to implement this.

**Comment by tharindu99** [comment]
No, wifi is optional. There are a lot of ways to do this without wifi and I would like to suggest one method for you. Create an mobile app that maintain your business card, when you want to publish that with near by people, just setup the distance and it will recorded in a db.
user_share (id, profile_url,location,allowed_distance). As a receiver, mobile app will only show the near by allowed users to you to get their business cards and when you select some one from that it will be appear in your mobile. Also you can visualize him in a radar circle getting your position as the center. This will be more easy and effective implementation for give project. Please let me know if you need any further clarification.
